language: python
os: linux
python:
- '3.8'
- '3.7'
jobs:
  include:
    - name: ubuntu-16
      dist: xenial
    - name: ubuntu-18
      dist: bionic
    - name: ubuntu-20
      dist: focal
before_script:
  - chmod +x "./build.sh"
script: ./build.sh
branches:
  only:
    - travis-ci
