language: python
os: linux
python:
- '3.8'
- '3.7'
before_install:
  - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
  - sudo apt-get -y update
  - sudo apt-get -y install freecad-python3 python3-pivy
  - pip install jupyter
before_script:
  - chmod +x "./build.sh"
jobs:
  include:
    - name: ubuntu-16
      dist: xenial
    - name: ubuntu-18
      dist: bionic
    - name: ubuntu-20
      dist: focal
script: ./build.sh
branches:
  only:
    - travis-ci
